version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5-jessie-browsers
    steps:
      - checkout
      - run:
          name: 'Setup'
          command: |
            virtualenv -p python3 ~/.virtualenvs/tap-marketo
            source ~/.virtualenvs/tap-marketo/bin/activate
            pip install .
            pip install pylint
      - run:
          name: 'Pylint'
          command: |
            source ~/.virtualenvs/tap-marketo/bin/activate
            pylint tap_marketo -d C,R
      - run:
          name: 'Unit Tests'
          command: |
            source ~/.virtualenvs/tap-marketo/bin/activate
            python -m unittest
